# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-06 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyear',
            name='slug',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
