# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("budgetportal", "0002_related-name-financial-year-spheres")]

    operations = [
        migrations.AlterField(
            model_name="sphere", name="name", field=models.CharField(max_length=200)
        ),
        migrations.AlterField(
            model_name="sphere", name="slug", field=models.SlugField(max_length=200)
        ),
        migrations.AlterUniqueTogether(
            name="sphere",
            unique_together=set(
                [("financial_year", "slug"), ("financial_year", "name")]
            ),
        ),
    ]
