# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 13:50
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("budgetportal", "0005_department-unique-together-constraints")]

    operations = [
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=200)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="department",
            name="government",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="budgetportal.Government",
            ),
        ),
        migrations.AlterField(
            model_name="government",
            name="sphere",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="governments",
                to="budgetportal.Sphere",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programmes",
                to="budgetportal.Department",
            ),
        ),
    ]
