# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 14:56


import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("budgetportal", "0010_add-govt-function-model")]

    operations = [
        migrations.AlterField(
            model_name="govtfunction",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="govtfunction",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                editable=False,
                max_length=200,
                populate_from=b"name",
                unique=True,
            ),
        ),
    ]
