# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-28 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("budgetportal", "0012_multi-department-votes")]

    operations = [
        migrations.AlterModelOptions(
            name="department", options={"ordering": ["vote_number", "name"]}
        ),
        migrations.AlterModelOptions(
            name="sphere", options={"ordering": ["-financial_year__slug", "name"]}
        ),
        migrations.AddField(
            model_name="department",
            name="website_url",
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(
                help_text=b"The department name must precisely match the text used in the Appropriation Bill. All datasets must be normalised to match this name. Beware that changing this name might cause a mismatch with already-published datasets which might need to be update to match this.",
                max_length=200,
            ),
        ),
    ]
