# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-13 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0015_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, to='budgetportal.Language'),
        ),
    ]
