# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-13 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0016_add-language'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
