# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-13 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0017_video_video_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='languages',
            new_name='language',
        ),
    ]
