# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-13 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0018_rename-language-on-video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[(b'hackathon', b'hackathon'), (b'dataquest', b'dataquest')], max_length=255)),
                ('province', models.CharField(choices=[(b'Gauteng', b'Gauteng'), (b'Western Cape', b'Western Cape')], max_length=255)),
                ('where', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('notes_url', models.URLField()),
                ('video_url', models.URLField()),
                ('rsvp_url', models.URLField()),
            ],
        ),
    ]
