# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-13 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0021_edit-event-fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='presentation_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
