# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-15 09:54


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("budgetportal", "0023_infrastructureprojectpart")]

    operations = [
        migrations.RemoveField(model_name="infrastructureprojectpart", name="amount"),
        migrations.RemoveField(
            model_name="infrastructureprojectpart", name="financial_year"
        ),
        migrations.RemoveField(
            model_name="infrastructureprojectpart", name="total_project_cost"
        ),
    ]
