# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-23 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("budgetportal", "0032_faq")]

    operations = [
        migrations.AlterModelOptions(
            name="faq",
            options={
                "ordering": ["the_order"],
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
            },
        ),
        migrations.AddField(
            model_name="faq",
            name="the_order",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
