# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-12 09:27


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("budgetportal", "0034_auto_20190923_1931")]

    operations = [
        migrations.CreateModel(
            name="ProvInfraProject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IRM_project_id", models.IntegerField(unique=True)),
                (
                    "project_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("province", models.CharField(blank=True, max_length=255, null=True)),
                ("department", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "local_municipality",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "district_municipality",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("latitude", models.CharField(blank=True, max_length=20, null=True)),
                ("longitude", models.CharField(blank=True, max_length=20, null=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                (
                    "estimated_construction_start_date",
                    models.DateField(blank=True, null=True),
                ),
                ("estimated_completion_date", models.DateField(blank=True, null=True)),
                (
                    "contracted_construction_end_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "estimated_construction_end_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "total_professional_fees",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "total_construction_costs",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "variation_orders",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "total_project_cost",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "expenditure_from_previous_years_professional_fees",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "expenditure_from_previous_years_construction_costs",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "expenditure_from_previous_years_total",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "project_expenditure_total",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "main_appropriation_professional_fees",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "adjustment_appropriation_professional_fees",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "main_appropriation_construction_costs",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "adjustment_appropriation_construction_costs",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "main_appropriation_total",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "adjustment_appropriation_total",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "actual_expenditure_q1",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "actual_expenditure_q2",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "actual_expenditure_q3",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "actual_expenditure_q4",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "budget_programme",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "primary_funding_source",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nature_of_investment",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "funding_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "program_implementing_agent",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "principle_agent",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "main_contractor",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "other_parties",
                    models.TextField(blank=True, max_length=510, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "financial_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prov_infra",
                        to="budgetportal.FinancialYear",
                    ),
                ),
            ],
        )
    ]
