# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-12 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("budgetportal", "0034_auto_20190923_1931")]

    operations = [
        migrations.CreateModel(
            name="ProvInfraProject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IRM_project_id", models.IntegerField(unique=True)),
                ("project_number", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("province", models.CharField(max_length=255)),
                ("department", models.CharField(max_length=255)),
                ("local_municipality", models.CharField(max_length=255)),
                ("district_municipality", models.CharField(max_length=255)),
                ("latitude", models.CharField(max_length=20)),
                ("longitude", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("estimated_construction_start_date", models.DateField()),
                ("estimated_completion_date", models.DateField()),
                ("contracted_construction_end_date", models.DateField()),
                ("estimated_construction_end_date", models.DateField()),
                (
                    "total_professional_fees",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                (
                    "total_construction_costs",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                (
                    "variation_orders",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                (
                    "total_project_cost",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                (
                    "expenditure_from_previous_years_professional_fees",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                (
                    "expenditure_from_previous_years_construction_costs",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                (
                    "expenditure_from_previous_years_total",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                (
                    "project_expenditure_total",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                (
                    "main_appropriation_professional_fees",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                (
                    "adjustment_appropriation_professional_fees",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                (
                    "main_appropriation_construction_costs",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                (
                    "adjustment_appropriation_construction_costs",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                (
                    "main_appropriation_total",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                (
                    "adjustment_appropriation_total",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                (
                    "actual_expenditure_q1",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                (
                    "actual_expenditure_q2",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                (
                    "actual_expenditure_q3",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                (
                    "actual_expenditure_q4",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                ("budget_programme", models.CharField(max_length=255)),
                ("primary_funding_source", models.CharField(max_length=255)),
                ("nature_of_investment", models.CharField(max_length=255)),
                ("funding_status", models.CharField(max_length=255)),
                ("program_implementing_agent", models.CharField(max_length=255)),
                ("principle_agent", models.CharField(max_length=255)),
                ("main_contractor", models.CharField(max_length=255)),
                ("other_parties", models.TextField(max_length=510)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "financial_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prov_infra",
                        to="budgetportal.FinancialYear",
                    ),
                ),
            ],
        )
    ]
