# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-25 02:38
from __future__ import unicode_literals

import budgetportal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("budgetportal", "0038_auto_20191024_1407")]

    operations = [
        migrations.AlterField(
            model_name="irmsnapshot",
            name="file",
            field=models.FileField(
                upload_to=budgetportal.models.irm_snapshot_file_path
            ),
        ),
        migrations.AlterUniqueTogether(
            name="provinfraprojectsnapshot",
            unique_together=set([("irm_snapshot", "project")]),
        ),
    ]
