# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-13 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0039_auto_20191025_0238'),
        ('budgetportal', '0038_auto_20191030_1437'),
    ]

    operations = [
    ]
