# Generated by Django 2.2.10 on 2020-03-04 13:35

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("budgetportal", "0042_auto_20200131_1500"),
    ]

    operations = [
        migrations.RenameField(
            model_name="provinfraprojectsnapshot",
            old_name="adjustment_appropriation_professional_fees",
            new_name="adjusted_appropriation_professional_fees",
        ),
        migrations.RenameField(
            model_name="provinfraprojectsnapshot",
            old_name="adjustment_appropriation_construction_costs",
            new_name="adjusted_appropriation_construction_costs",
        ),
        migrations.RenameField(
            model_name='infrastructureprojectpart',
            old_name='total_project_cost',
            new_name='estimated_total_project_cost',
        ),
        migrations.RenameField(
            model_name='provinfraprojectsnapshot',
            old_name='adjustment_appropriation_total',
            new_name='adjusted_appropriation_total',
        ),
        migrations.RenameField(
            model_name='provinfraprojectsnapshot',
            old_name='total_project_cost',
            new_name='estimated_total_project_cost',
        )
    ]
