# Generated by Django 2.2.10 on 2020-02-29 16:00

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0042_auto_20200131_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchPageCSVDownloadRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, unique=True)),
                ('projects', models.ManyToManyField(to='budgetportal.ProvInfraProjectSnapshot')),
            ],
        ),
    ]
