# Generated by Django 2.2.10 on 2020-03-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0043_auto_20200304_1335'),
        ('budgetportal', '0043_infrastructureprojectpart_ppp_fields'),
    ]

    operations = [
    ]
