# Generated by Django 2.2.10 on 2020-03-01 12:15

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("budgetportal", "0043_auto_20200229_1600"),
    ]

    operations = [
        migrations.RenameField(
            model_name="searchpagecsvdownloadrequest",
            old_name="projects",
            new_name="projects_snapshots",
        )
    ]
