# Generated by Django 2.2.10 on 2020-03-05 09:38

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("budgetportal", "0043_auto_20200304_1335"),
    ]

    operations = [
        migrations.RenameField(
            model_name="infrastructureprojectpart",
            old_name="estimated_total_project_cost",
            new_name="total_project_cost",
        ),
    ]
