# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 06:26
from __future__ import unicode_literals

import ckeditor.fields
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0043_auto_20200208_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock())]),
        ),
    ]
