# Generated by Django 2.2.10 on 2020-03-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0043_auto_20200303_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infrastructureprojectpart',
            old_name='sphere',
            new_name='administration_type',
        ),
        migrations.RenameField(
            model_name='infrastructureprojectpart',
            old_name='department',
            new_name='government_institution',
        ),
        migrations.AddField(
            model_name='infrastructureprojectpart',
            name='date_of_close',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='infrastructureprojectpart',
            name='duration',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='infrastructureprojectpart',
            name='financing_structure',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='infrastructureprojectpart',
            name='form_of_payment',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='infrastructureprojectpart',
            name='partnership_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='infrastructureprojectpart',
            name='project_value_rand_million',
            field=models.CharField(default='', max_length=255),
        ),
    ]
