# Generated by Django 2.2.10 on 2020-03-10 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0043_auto_20200310_1720'),
        ('budgetportal', '0043_auto_20200304_1335'),
    ]

    operations = [
    ]
