# Generated by Django 2.2.10 on 2020-03-11 14:41

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("budgetportal", "0044_auto_20200311_1417"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq", name="content", field=wagtail.core.fields.RichTextField(),
        ),
    ]
