# Generated by Django 2.2.10 on 2020-03-09 12:19

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgetportal", "0044_merge_20200306_0758"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infrastructureprojectpart",
            name="amount_rands",
            field=models.BigIntegerField(blank=True, null=True, default=None),
        ),
    ]
