# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-14 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0019_delete_filter"),
        ("wagtailcore", "0040_page_draft_title"),
        ("budgetportal", "0045_auto_20200214_1456"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuideIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                ("intro", wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={"abstract": False,},
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="LearningIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "body",
                    wagtail.wagtailcore.fields.StreamField(
                        [
                            (
                                b"section",
                                wagtail.wagtailcore.blocks.StructBlock(
                                    [
                                        (
                                            b"presentation_class",
                                            wagtail.wagtailcore.blocks.ChoiceBlock(
                                                choices=[
                                                    (b"is-default", b"Default"),
                                                    (
                                                        b"is-invisible",
                                                        b"No background/border",
                                                    ),
                                                    (b"is-bevel", b"Bevel"),
                                                ]
                                            ),
                                        ),
                                        (
                                            b"heading",
                                            wagtail.wagtailcore.blocks.CharBlock(),
                                        ),
                                        (
                                            b"content",
                                            wagtail.wagtailcore.blocks.RichTextBlock(),
                                        ),
                                    ]
                                ),
                            ),
                            (b"html", wagtail.wagtailcore.blocks.RawHTMLBlock()),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={"abstract": False,},
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="PostIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                ("intro", wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={"abstract": False,},
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="WagtailHomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
            ],
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="GuidePage",
            fields=[],
            options={"abstract": False,},
            bases=("budgetportal.page",),
        ),
        migrations.CreateModel(
            name="PostPage",
            fields=[],
            options={"abstract": False,},
            bases=("budgetportal.page",),
        ),
        migrations.AddField(
            model_name="page",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
            ),
        ),
    ]
