# Generated by Django 2.2.10 on 2020-03-09 15:46

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0045_auto_20200309_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructureprojectpart',
            name='date_of_close',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructureprojectpart',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructureprojectpart',
            name='financing_structure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructureprojectpart',
            name='form_of_payment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructureprojectpart',
            name='partnership_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructureprojectpart',
            name='project_value_rand_million',
            field=models.CharField(blank=True, max_length=255, null=True),
        )
    ]
