# Generated by Django 2.2.10 on 2020-03-13 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0046_auto_20200309_1546'),
        ('budgetportal', '0046_guideindexpage_guidepage_learningindexpage_postindexpage_postpage'),
    ]

    operations = [
    ]
