# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-14 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailforms", "0003_capitalizeverbose"),
        ("wagtailcore", "0040_page_draft_title"),
        ("wagtailredirects", "0005_capitalizeverbose"),
        ("budgetportal", "0046_auto_20200214_1527"),
    ]

    operations = [
        migrations.DeleteModel(name="GuidePage",),
        migrations.RemoveField(model_name="page", name="image",),
        migrations.RemoveField(model_name="page", name="page_ptr",),
        migrations.DeleteModel(name="PostPage",),
        migrations.DeleteModel(name="Page",),
    ]
