# Generated by Django 2.2.10 on 2020-03-14 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0047_auto_20200313_0626'),
        ('budgetportal', '0047_auto_20200313_1911'),
    ]

    operations = [
    ]
