# Generated by Django 2.2.10 on 2020-03-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgetportal", "0048_merge_20200314_1035"),
    ]

    operations = [
        migrations.AddField(
            model_name="infraprojectsnapshot",
            name="sector",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
