# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-15 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0048_guidepage_postpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_slug', models.SlugField(max_length=200)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('external_url_description', models.TextField(blank=True, help_text=b'Only shown if External URL is used. This may be truncated so use a short description that will also be seen on the external page.', null=True)),
                ('guide_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetportal.GuidePage')),
            ],
        ),
    ]
