# Generated by Django 2.2.10 on 2020-03-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgetportal", "0049_infraprojectsnapshot_sector"),
    ]

    operations = [
        migrations.AddField(
            model_name="infraproject",
            name="sphere_slug",
            field=models.CharField(default="provincial", max_length=100),
            preserve_default=False,
        ),
    ]
