# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-15 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0049_categoryguide'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryguide',
            name='external_url_title',
            field=models.CharField(blank=True, help_text=b'Only shown if External URL is used. This may be truncated so use a short description that will also be seen on the external page.', max_length=200, null=True),
        ),
    ]
