# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-15 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0050_categoryguide_external_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryguide',
            name='category_slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
