# Generated by Django 2.2.10 on 2020-03-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0051_auto_20200314_1522'),
        ('budgetportal', '0048_auto_20200313_2011'),
    ]

    operations = [
    ]
