# Generated by Django 2.2.10 on 2020-03-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budgetportal", "0054_auto_20200318_1943"),
        ("budgetportal", "0054_custompage_body"),
    ]

    operations = []
