# Generated by Django 2.2.10 on 2020-03-24 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0056_auto_20200324_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidepage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='guidepage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='guidepage',
            name='updated_at',
        ),
    ]
