# Generated by Django 2.2.10 on 2020-03-24 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0057_auto_20200324_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wagtailhomepage',
            options={'verbose_name': 'Homepage'},
        ),
        migrations.RemoveField(
            model_name='postpage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='postpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='postpage',
            name='updated_at',
        ),
    ]
