# Generated by Django 2.2.10 on 2020-04-16 12:13

import wagtail.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgetportal", "0058_auto_20200327_1414"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=1024)),
                ("content", wagtail.core.fields.RichTextField()),
                (
                    "notice_order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, editable=False
                    ),
                ),
            ],
            options={
                "ordering": ["notice_order"],
            },
        ),
    ]
