# Generated by Django 2.2.10 on 2020-04-16 12:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budgetportal", "0059_notice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="notice",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
