# Generated by Django 2.2.10 on 2020-07-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0061_auto_20200714_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='InYearMonitoringResourceLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'In-year monitoring resource link',
                'verbose_name_plural': 'In-year monitoring resource links',
            },
        ),
        migrations.CreateModel(
            name='PerformanceResourceLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Performance resource link',
                'verbose_name_plural': 'Performance resource links',
            },
        ),
        migrations.CreateModel(
            name='ProcurementResourceLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Procurement resource link',
                'verbose_name_plural': 'Procurement resource links',
            },
        ),
    ]
