# Generated by Django 2.2.10 on 2020-07-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "budgetportal",
            "0062_inyearmonitoringresourcelink_performanceresourcelink_procurementresourcelink",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="inyearmonitoringresourcelink",
            name="resource_link_order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, help_text="Links are shown in this order."
            ),
        ),
        migrations.AddField(
            model_name="inyearmonitoringresourcelink",
            name="sphere_slug",
            field=models.CharField(
                choices=[
                    ("all", "all"),
                    ("national", "national"),
                    ("provincial", "provincial"),
                ],
                default="all",
                help_text="Only show on pages for this sphere or all spheres.",
                max_length=100,
                verbose_name="Sphere",
            ),
        ),
        migrations.AddField(
            model_name="performanceresourcelink",
            name="resource_link_order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, help_text="Links are shown in this order."
            ),
        ),
        migrations.AddField(
            model_name="performanceresourcelink",
            name="sphere_slug",
            field=models.CharField(
                choices=[
                    ("all", "all"),
                    ("national", "national"),
                    ("provincial", "provincial"),
                ],
                default="all",
                help_text="Only show on pages for this sphere or all spheres.",
                max_length=100,
                verbose_name="Sphere",
            ),
        ),
        migrations.AddField(
            model_name="procurementresourcelink",
            name="resource_link_order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, help_text="Links are shown in this order."
            ),
        ),
        migrations.AddField(
            model_name="procurementresourcelink",
            name="sphere_slug",
            field=models.CharField(
                choices=[
                    ("all", "all"),
                    ("national", "national"),
                    ("provincial", "provincial"),
                ],
                default="all",
                help_text="Only show on pages for this sphere or all spheres.",
                max_length=100,
                verbose_name="Sphere",
            ),
        ),
    ]
