# Generated by Django 2.2.28 on 2023-02-17 14:33

import budgetportal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgetportal", "0065_showcaseitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showcaseitem",
            name="file",
            field=models.FileField(
                upload_to=budgetportal.models.showcase_item_file_path
            ),
        ),
    ]
