# Generated by Django 2.2.28 on 2023-02-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0067_auto_20230219_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showcaseitem',
            options={'ordering': ['item_order']},
        ),
        migrations.AddField(
            model_name='showcaseitem',
            name='item_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
