# Generated by Django 2.2.28 on 2023-02-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgetportal", "0069_showcaseitem_cta_enabled_2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="showcaseitem",
            name="cta_enabled_2",
        ),
        migrations.AlterField(
            model_name="showcaseitem",
            name="cta_text_2",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Call to action text 2",
            ),
        ),
    ]
