# Generated by Django 2.2.20 on 2023-12-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0071_auto_20230605_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenuitem',
            name='highlight_as_new',
            field=models.BooleanField(default=False),
        ),
    ]
