# Generated by Django 2.2.20 on 2024-01-25 09:33

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0072_mainmenuitem_highlight_as_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The public entity name must precisely match the text used . All datasets must be normalised to match this name. Beware that changing this name might cause a mismatch with already-published datasets which might need to be update to match this.', max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=True, max_length=200, populate_from='name')),
                ('intro', models.TextField(default='A description of this public entity.')),
                ('pfma', models.CharField(choices=[('1', '1'), ('2', '2'), ('3A', '3A'), ('3B', '3B'), ('NL', 'Not listed')], max_length=2)),
                ('functiongroup1', models.CharField(blank=True, choices=[('GPS', 'General public services'), ('ED', 'Economic development'), ('LAC', 'Learning and culture'), ('SD', 'Social development'), ('PAS', 'Peace and security'), ('CD', 'Community development'), ('H', 'Health')], max_length=3, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetportal.Department')),
                ('government', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_entities', to='budgetportal.Government')),
            ],
            options={
                'verbose_name_plural': 'public entities',
                'ordering': ['name'],
                'unique_together': {('government', 'slug'), ('government', 'name')},
            },
        ),
    ]
