# Generated by Django 2.2.20 on 2024-03-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0073_publicentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicentity',
            name='pfma',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3A', '3A'), ('3B', '3B'), ('NL', 'Not listed')], max_length=10),
        ),
    ]
