# Generated by Django 2.2.20 on 2024-03-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0074_auto_20240318_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicentity',
            name='functiongroup1',
            field=models.CharField(blank=True, choices=[('GPS', 'General public services'), ('ED', 'Economic development'), ('LAC', 'Learning and culture'), ('SD', 'Social development'), ('PAS', 'Peace and security'), ('CD', 'Community development'), ('H', 'Health')], max_length=200, null=True),
        ),
    ]
