# Generated by Django 2.2.20 on 2024-03-18 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0075_auto_20240318_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicEntityExpenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('functiongroup2', models.CharField(blank=True, choices=[('GPS', 'General public services'), ('ED', 'Economic development'), ('LAC', 'Learning and culture'), ('SD', 'Social development'), ('PAS', 'Peace and security'), ('CD', 'Community development'), ('H', 'Health')], max_length=200, null=True)),
                ('expenditure_type', models.CharField(blank=True, max_length=200, null=True)),
                ('consol_indi', models.CharField(blank=True, max_length=10, null=True)),
                ('economic_classification1', models.CharField(blank=True, max_length=200, null=True)),
                ('economic_classification2', models.CharField(blank=True, max_length=200, null=True)),
                ('economic_classification3', models.CharField(blank=True, max_length=200, null=True)),
                ('economic_classification4', models.CharField(blank=True, max_length=200, null=True)),
                ('economic_classification5', models.CharField(blank=True, max_length=200, null=True)),
                ('economic_classification6', models.CharField(blank=True, max_length=200, null=True)),
                ('budget_phase', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=20)),
                ('public_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetportal.PublicEntity')),
            ],
        ),
    ]
