# Generated by Django 2.2.20 on 2024-03-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0076_publicentityexpenditure'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicentity',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
    ]
