# Generated by Django 2.2.20 on 2024-04-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0077_publicentity_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicentity',
            name='intro',
            field=models.TextField(blank=True, default=''),
        ),
    ]
