FROM python:3.7
ENV PYTHONUNBUFFERED 1
RUN apt-get update && \
    apt-get install -y chromium-driver

RUN mkdir /code
WORKDIR /code
COPY requirements-test.txt /code/
COPY requirements.txt /code/
RUN pip install -U setuptools==45.3.0
RUN pip install -r requirements.txt
RUN pip install -r requirements-test.txt
COPY . /code/
