FROM python:3.7
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
COPY requirements-test.txt /code/
COPY requirements.txt /code/
RUN pip uninstall -y setuptools
RUN pip install setuptools==45.0.0
RUN pip install -r requirements.txt
RUN pip install -r requirements-test.txt
COPY . /code/
