FROM python:2
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
COPY requirements-test.txt /code/
COPY requirements.txt /code/
RUN pip install -r requirements.txt
RUN pip install -r requirements-test.txt
COPY . /code/
RUN apt-get update && \
    apt-get install -y chromium-driver