# Generated by Django 2.2.28 on 2023-06-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iymfileupload',
            name='status',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
