# Generated by Django 2.2.28 on 2023-06-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iym', '0002_iymfileupload_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='iymfileupload',
            name='task_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
