# Generated by Django 2.2.28 on 2023-07-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iym", "0003_iymfileupload_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iymfileupload",
            name="process_completed",
            field=models.BooleanField(),
        ),
    ]
