# Generated by Django 2.2.28 on 2023-07-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iym", "0004_auto_20230703_1449"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iymfileupload",
            name="process_completed",
            field=models.BooleanField(default=False),
        ),
    ]
