# Generated by Django 2.2.20 on 2022-11-29 07:50

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import performance.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgetportal', '0064_auto_20200728_1054'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_q', '0009_auto_20171009_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='EQPRSFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=performance.models.eqprs_file_path)),
                ('file_validation_report', django.contrib.postgres.fields.jsonb.JSONField()),
                ('import_report', models.TextField()),
                ('num_imported', models.IntegerField(null=True)),
                ('num_not_imported', models.IntegerField(null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_q.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.TextField()),
                ('q1_target', models.TextField(blank=True)),
                ('q1_actual_outcome', models.TextField(blank=True)),
                ('q1_deviation_reason', models.TextField(blank=True)),
                ('q1_corrective_action', models.TextField(blank=True)),
                ('q1_national_comments', models.TextField(blank=True)),
                ('q1_otp_comments', models.TextField(blank=True)),
                ('q1_dpme_coordinator_comments', models.TextField(blank=True)),
                ('q1_treasury_comments', models.TextField(blank=True)),
                ('q2_target', models.TextField(blank=True)),
                ('q2_actual_outcome', models.TextField(blank=True)),
                ('q2_deviation_reason', models.TextField(blank=True)),
                ('q2_corrective_action', models.TextField(blank=True)),
                ('q2_national_comments', models.TextField(blank=True)),
                ('q2_otp_comments', models.TextField(blank=True)),
                ('q2_dpme_coordinator_comments', models.TextField(blank=True)),
                ('q2_treasury_comments', models.TextField(blank=True)),
                ('q3_target', models.TextField(blank=True)),
                ('q3_actual_outcome', models.TextField(blank=True)),
                ('q3_deviation_reason', models.TextField(blank=True)),
                ('q3_corrective_action', models.TextField(blank=True)),
                ('q3_national_comments', models.TextField(blank=True)),
                ('q3_otp_comments', models.TextField(blank=True)),
                ('q3_dpme_coordinator_comments', models.TextField(blank=True)),
                ('q3_treasury_comments', models.TextField(blank=True)),
                ('q4_target', models.TextField(blank=True)),
                ('q4_actual_outcome', models.TextField(blank=True)),
                ('q4_deviation_reason', models.TextField(blank=True)),
                ('q4_corrective_action', models.TextField(blank=True)),
                ('q4_national_comments', models.TextField(blank=True)),
                ('q4_otp_comments', models.TextField(blank=True)),
                ('q4_dpme_coordinator_comments', models.TextField(blank=True)),
                ('q4_treasury_comments', models.TextField(blank=True)),
                ('sector', models.TextField(blank=True)),
                ('programme_name', models.TextField(blank=True)),
                ('subprogramme_name', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('annually', 'Annually'), ('quarterly', 'Quarterly')], max_length=9)),
                ('type', models.TextField(blank=True)),
                ('subtype', models.TextField(blank=True)),
                ('mtsf_outcome', models.TextField(blank=True)),
                ('uid', models.TextField(blank=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_values', to='budgetportal.Department')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_values', to='performance.EQPRSFileUpload')),
            ],
            options={
                'unique_together': {('department', 'indicator_name')},
            },
        ),
    ]
