# Generated by Django 2.2.20 on 2022-11-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0002_auto_20221129_0819"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eqprsfileupload",
            name="file_validation_report",
        ),
    ]
