# Generated by Django 2.2.20 on 2022-12-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0004_auto_20221205_1147"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
