# Generated by Django 2.2.20 on 2022-12-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0005_indicator_created_at"),
        ("performance", "0004_auto_20221130_2138"),
    ]

    operations = []
