# Generated by Django 2.2.20 on 2023-01-04 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0007_auto_20221213_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eqprsfileupload',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
