# Generated by Django 2.2.28 on 2023-02-02 10:43

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0010_eqprsfileupload_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="content_search",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="indicator",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["content_search"], name="performance_content_b5accd_gin"
            ),
        ),
    ]
