# Generated by Django 2.2.28 on 2023-02-02 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0012_auto_20230202_1121"),
    ]

    migration = """
        CREATE TRIGGER content_search_update BEFORE INSERT OR UPDATE
        ON performance_indicator FOR EACH ROW EXECUTE PROCEDURE
        tsvector_update_trigger(
            content_search, 'pg_catalog.english',
            q1_target, q1_actual_output, q1_deviation_reason, q1_corrective_action,
            q1_national_comments, q1_otp_comments, q1_dpme_coordinator_comments,
            q1_treasury_comments,

            q2_target, q2_actual_output, q2_deviation_reason, q2_corrective_action,
            q2_national_comments, q2_otp_comments, q2_dpme_coordinator_comments,
            q2_treasury_comments,

            q3_target, q3_actual_output, q3_deviation_reason, q3_corrective_action,
            q3_national_comments, q3_otp_comments, q3_dpme_coordinator_comments,
            q3_treasury_comments,

            q4_target, q4_actual_output, q4_deviation_reason, q4_corrective_action,
            q4_national_comments, q4_otp_comments, q4_dpme_coordinator_comments,
            q4_treasury_comments,

            annual_target, annual_aggregate_output, annual_pre_audit_output,
            annual_deviation_reason, annual_corrective_action,
            annual_national_comments, annual_otp_comments, annual_dpme_coordinator_comments,
            annual_treasury_comments, annual_audited_output,

            sector, programme_name, subprogramme_name, frequency, type, subtype,
            mtsf_outcome, cluster
    );
        -- Force triggers to run and populate the content_search column.
        UPDATE performance_indicator set ID = ID;
    """

    reverse_migration = """
        DROP TRIGGER content_search_update ON performance_indicator;
    """

    operations = [migrations.RunSQL(migration, reverse_migration)]
