# Generated by Django 2.2.28 on 2023-02-23 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0014_eqprsdepartmentalias"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eqprsdepartmentalias",
            options={"verbose_name_plural": "Eqprs department aliases"},
        ),
    ]
