# Generated by Django 2.2.28 on 2023-02-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0015_auto_20230223_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eqprsdepartmentalias',
            name='alias',
            field=models.CharField(max_length=200),
        ),
    ]
