name: Budget portal

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: "13.14.0"

    - name: Build frontend assets
      run: |
        npm install -g yarn@1.21.1
        yarn
        yarn build

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Run tests
      run: |
        docker-compose run --rm test python manage.py collectstatic --no-input
        docker-compose run --rm test
        docker-compose run --rm app black --check --diff budgetportal manage.py discourse performance

    - name: Dump dependency logs for debugging
      run: |
        docker-compose logs db solr minio
