name: Budget portal

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: "14.21.3"

    - name: Build frontend assets
      run: |
        npm install -g yarn@1.21.1
        yarn
        yarn build

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build images
      run: |
        docker-compose build

    - name: Run tests
      run: |
        docker-compose run --rm app python manage.py collectstatic --no-input
        docker-compose run --rm -e DJANGO_Q_SYNC=TRUE app python manage.py test budgetportal.tests.test_admin_departments_upload  budgetportal.tests.test_department_instance_loader  budgetportal.tests.test_featured_projects  budgetportal.tests.test_management_commands  budgetportal.tests.test_summaries  budgetportal.tests.test_datasets  budgetportal.tests.test_department_page  budgetportal.tests.test_guides_pages budgetportal.tests.test_pages  budgetportal.tests.test_bulk_upload  budgetportal.tests.test_department  budgetportal.tests.test_featured_infra_projects  budgetportal.tests.test_import_export_widgets budgetportal.tests.test_posts_pages
        docker-compose run --rm app black --check --diff budgetportal manage.py discourse performance iym

    - name: Dump dependency logs for debugging
      if: ${{ failure() }}
      run: |
        docker-compose logs db solr minio selenium
